// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg7FV8tI5EHBMCA3EH9ac7IFr4FMGRJLg',
    appId: '1:901242723335:web:43999859b4add54dc05ea2',
    messagingSenderId: '901242723335',
    projectId: 'qonect-25f17',
    authDomain: 'qonect-25f17.firebaseapp.com',
    storageBucket: 'qonect-25f17.appspot.com',
    measurementId: 'G-N6K2ZZS34Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX37odioy-3SD1n7B-aaOe5BxEnE1xHpo',
    appId: '1:901242723335:android:f2f7a0961cdba1a6c05ea2',
    messagingSenderId: '901242723335',
    projectId: 'qonect-25f17',
    storageBucket: 'qonect-25f17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADQxrBFhbufbmI96NtpfxOnsG-pGRLN6g',
    appId: '1:901242723335:ios:7149a7dc7653c1aac05ea2',
    messagingSenderId: '901242723335',
    projectId: 'qonect-25f17',
    storageBucket: 'qonect-25f17.appspot.com',
    iosBundleId: 'com.example.qonectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADQxrBFhbufbmI96NtpfxOnsG-pGRLN6g',
    appId: '1:901242723335:ios:7149a7dc7653c1aac05ea2',
    messagingSenderId: '901242723335',
    projectId: 'qonect-25f17',
    storageBucket: 'qonect-25f17.appspot.com',
    iosBundleId: 'com.example.qonectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg7FV8tI5EHBMCA3EH9ac7IFr4FMGRJLg',
    appId: '1:901242723335:web:f3d8d5cbaf0c5657c05ea2',
    messagingSenderId: '901242723335',
    projectId: 'qonect-25f17',
    authDomain: 'qonect-25f17.firebaseapp.com',
    storageBucket: 'qonect-25f17.appspot.com',
    measurementId: 'G-B3EBR1XMK1',
  );
}
